on: push
jobs:
  cicd:
    uses: internetarchive/cicd/.github/workflows/cicd.yml@main
    with:
      NOMAD_VAR_HOSTNAMES: '["emularity-bios"]'
      NOMAD_VAR_PORTS: '{ 80 = "http" }'
    secrets:
      NOMAD_TOKEN: ${{ secrets.NOMAD_TOKEN }}
